### ISSUE TITLE
Nuxt Fatal Error

### ISSUE THREAD

**Issue by NewVo1d** [rymcu/nebula#56]
作者你好，nebula拉取最新的代码后（PR #52 及之前是正常的），npm run dev命令后显示vue版本不一致，报错具体如下：

```
$ npm run dev

> nebula@1.0.0 dev
> nuxt


 FATAL                                                                                                                                                     21:36:37

Vue packages version mismatch:

- vue@2.7.13
- vue-server-renderer@2.6.14

This may cause things to work incorrectly. Make sure to use the same version for both.


  
  Vue packages version mismatch:
  
  - vue@2.7.13
  - vue-server-renderer@2.6.14
  
  This may cause things to work incorrectly. Make sure to use the same version for both.
  
  at Object.<anonymous> (node_modules\vue-server-renderer\index.js:8:9)
  at Module.o._compile (node_modules\jiti\dist\v8cache.js:2:2778)
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
  at Module.load (node:internal/modules/cjs/loader:981:32)
  at Function.Module._load (node:internal/modules/cjs/loader:822:12)
  at Module.require (node:internal/modules/cjs/loader:1005:19)
  at n (node_modules\jiti\dist\v8cache.js:2:2472)
  at Object.<anonymous> (node_modules\@nuxt\vue-renderer\dist\vue-renderer.js:19:27)
  at Module.o._compile (node_modules\jiti\dist\v8cache.js:2:2778)
  at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)


   ╭────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                            │
   │   ✖ Nuxt Fatal Error                                                                       │
   │                                                                                            │
   │   Error:                                                                                   │
   │                                                                                            │
   │   Vue packages version mismatch:                                                           │
   │                                                                                            │
   │   - vue@2.7.13                                                                             │
   │   - vue-server-renderer@2.6.14                                                             │
   │                                                                                            │
   │   This may cause things to work incorrectly. Make sure to use the same version for both.   │
   │                                                                                            │
   │                                                                                            │
   ╰────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by ronger-x** [comment]
把 node_modules 删除,重新执行 yarn install 试试,我刚 clone 了一份最新代码测试是正常的

**Comment by NewVo1d** [comment]
感谢

**Comment by ronger-x** [comment]
🍻 周末愉快,有问题随时反馈
